services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

  node-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      MONGO_URL: mongodb://admin:secret@mongodb:27017/wildhaven-db?authSource=admin
    ports:
      - "3800:3800"
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./backend/:/usr/src/app # Sincroniza tu código del backend con la carpeta /app del contenedor

  angular-app:
    build:
      context: ./frontend/WildHaven/
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"
    networks:
      - app-network
    volumes:
      - ./frontend/WildHaven/:/usr/src/frontend 
      - /usr/src/frontend/node_modules  # Evita que el mapeo local sobrescriba node_modules
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
