version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push


  node-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile  # Asegúrate de que tu Dockerfile esté en el mismo directorio
    container_name: node-app
    environment:
      MONGO_URL: mongodb://admin:secret@mongodb:27017/wildhaven-db?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push


  angular-app:
    build:
      context: ./frontend/WildHaven/
      dockerfile: Dockerfile  # Asegúrate de que tu Dockerfile esté en el mismo directorio
    container_name: angular-app
    ports:
      - "4200:4200"  # Exponer el puerto 80 (donde Nginx sirve la app de Angular) al puerto 420
    networks:
      - app-network
    logging:
      driver: loki
      options:
        loki-url: http://loki:3100/loki/api/v1/push


  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/etc/loki
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana


  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
      
      
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  grafana-data:
    driver: local
  loki-data:
    driver: local