server:
  http_listen_port: 9080
  log_level: info

clients:
  - url: http://loki:3100/loki/api/v1/push  # Dirección del contenedor Loki

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log  # Ruta de logs de contenedores Docker
